#' Add a step functions to an existing plot
#'
#' A function to add a step function to the current plot. This function is
#' similar to the default \code{plot} of a function generated by
#' \code{\link{stepfun}} with the difference that the domain of the function
#' can be specified. More precisely, the first and last entries of the vector
#' \code{x} determine the range of the domain, i.e. the leftmost line in the
#' plot starts at \code{x[1]} and the rightmost line ends at \code{x[N]} where
#' \code{N} denotes the length of \code{x}. The x-coordinates of the jump points
#' are given by \code{x[2:N]} wheres the y-coordinate of each line is given
#' by the vector \code{y}. In particular \code{y} has to be a vector of length
#' \code{N-1}.
#'
#' @param x,y vectors of x- and y- coordinates to specify the domain, jump points
#' and jump heights in the step function.
#' @param lwd,lty,col,cex.points,pch plot options for line width, line type,
#' color, size of points and type of points; see \code{\link{par}} for more details.
#' @param verticals a boolean variable that indicates whether vertical lines
#' should be added at all jump points.
#' @param do.points a boolean variable that indicates whether points
#' should be plotted at each jump point. The position of the points
#' depend on the choice for \code{cadlag}
#' @param cadlag a boolean variable to choose whether the step function should
#' be cadlag (right continous with left limits) or ladcag (left continous with
#' right limits). Has no effect if \code{do.points=FALSE}.
#'
#' @return NULL
#'
#' @seealso \code{\link{plotstep}}
#'
#' @export

addstepfun <- function(x,y, lwd=par("lwd"), lty=par("lty"), col="black",
                       verticals=TRUE, do.points=FALSE, cex.points=par("cex"),
                       pch=par("pch"), cadlag=TRUE){

  if(length(x)!=length(y)+1){
    stop("Mismatching data dimensions: length(x)!=length(y)+1")
  }
  for(i in 1:length(y)){
    lines(x[i:(i+1)], c(y[i],y[i]), col=col, lty=lty, lwd=lwd)

    if(verticals & (i<length(y))){
      lines(c(x[i+1],x[i+1]), y[i:(i+1)], col=col, lty=lty, lwd=lwd)
    }
  }
  if(do.points){
    points(x[2:(length(x)-1)],y[1:(length(y)-1)+cadlag], pch=pch, cex=cex.points)
  }

  return(invisible(NULL))
}


#' Plot of a step functions
#'
#' A wrapper function to create a new plot and perfom the \code{\link{addstepfun}}
#' function.
#'
#' @param x,y,lwd,lty,col,cex.points,pch,verticals,do.points,cadlag paramter
#' choices in \code{\link{addstepfun}}
#' @param xlim,ylim,xlab,ylab,main,cex,cex.lab further plot options; see \code{\link{plot}}
#' for more details.
#'
#' @return NULL
#'
#' @seealso \code{\link{addstepfun}}
#'
#' @export


plotstep <- function(x, y, xlim=c(x[1], x[length(x)]), ylim=c(y[1],y[length(y)]),
                     xlab="x", ylab="y", main="", lwd=par("lwd"), lty=par("lty"),
                     col="black", verticals=TRUE, do.points=FALSE,
                     cex=par("cex"), cex.lab=cex,
                     cex.points=cex, pch=par("pch"), cadlag=TRUE)
{
  plot(NULL,NULL, xlim=xlim, ylim=ylim, xlab=xlab, ylab=ylab, main=main,
       cex=cex, cex.lab=cex.lab)
  if(length(x)!=length(y)+1){
    stop("Mismatching data dimensions: length(x)!=length(y)+1")
  }

  addstepfun(x=x,y=y, lwd=lwd, lty=lty, col=col, verticals=verticals,
             do.points=do.points, cex.points=cex.points,
             pch=pch, cadlag=cadlag)


  return(invisible(NULL))
}
